# landscape short name
landscapeName: magma
# Update with your membership structure
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: Platinum
   - name: Ecosystem Membership
     category: Ecosystem
   - name: Associate Membership
     category: Associate
# SF Project record ID for your project
project: 00O2M0000099GqcUAE # Open Mainframe Project
# Name of category for members 
landscapeMemberCategory: Magma Core Foundation Member Company
